backend:
  name: git-gateway
  branch: main  # gałąź w repo, do której mają trafiać zmiany

media_folder: "images/uploads"  # folder w projekcie na zdjęcia
public_folder: "/images/uploads"

collections:
  - name: "aktualnosci"
    label: "Aktualności"
    folder: "posts/aktualnosci"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Obrazek", name: "image", widget: "image"}
      - {label: "Treść", name: "body", widget: "markdown"}
